spring.application.name=seguranca
# Configuração do Banco de Dados em Memória (H2)
# Essa configuração cria um banco de dados novo toda vez que o sistema inicia
spring.datasource.url=jdbc:h2:mem:vendasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuração do JPA/Hibernate
# O H2 gera as tabelas automaticamente com base nas entidades (modelos)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Configura o H2 para ficar visível no console 
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console